### ISSUE TITLE
Bug: On Destination - Issue with loading credentials via pipeline yaml. 

### ISSUE THREAD

**Issue by anna-cross** [conduitio-labs/conduit-connector-gcp-pubsub#212]
### Bug description

When running conduit with the pipeline yaml below, the connector seems to be unable to authenticate and validate the PK provided. 
```

version: 2.0
pipelines:
  - id: clickhouse-to-google-pub
    status: running
    connectors:
      - id: sf.in
        type: source
        plugin: standalone:clickhouse@v0.1.0-41-g606af59
        settings:
          url: # ex https://default:PASSWORD@ORG.us-east-1.aws.clickhouse.cloud:8443/default?secure
          table: #test
          orderingColumn: #name
          batchSize: #10
      - id: sf.out
        type: destination
        plugin: standalone:gcp-pubsub@0299d3b-dirty
        settings:
          privateKey: # the entirity of private key, must start with -----BEGIN PRIVATE KEY----- and end with -----END PRIVATE KEY-----\n
          clientEmail: # ex - meroxatest@meroxa.iam.gserviceaccount.com
          projectId: # meroxa
          topicId: # test

```
          

However when passing following json as options in code manually in client/pubsub.go, the same private key provided seems to work. 

`options := `{
		"type": "service_account",
		"project_id": "meroxa",
		"private_key_id": "b5c7aa1bc56e1759bb781ca53406016b6c587cc1",
		"private_key": "PRIVATEKEY",
		"client_email": "meroxatest@meroxa.iam.gserviceaccount.com",
		"client_id": "109884669801399525038",
		"auth_uri": "https://accounts.google.com/o/oauth2/auth",
		"token_uri": "https://oauth2.googleapis.com/token",
		"auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
		"client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/meroxatest%40meroxa.iam.gserviceaccount.com",
		"universe_domain": "googleapis.com"
	  }
	  `
	cli, err := pubsub.NewClient(ctx, cfg.ProjectID, option.WithCredentialsJSON([]byte(options)))
`

### Steps to reproduce

1. Use the pipeline yaml above in your local conduit with clickhouse and pubsub credentials 
2. Try passing your pubsub PK in the yaml 

### Version

v0.1.0
